services:
  web:
    image: ghcr.io/lewis159/springsteen-news:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.springsteen.rule=Host(`bruce.bentech.dev`)"
      - "traefik.http.routers.springsteen.entrypoints=websecure"
      - "traefik.http.routers.springsteen.tls.certresolver=letsencrypt"
      - "traefik.http.services.springsteen.loadbalancer.server.port=5000"
